### ISSUE TITLE
Installs fail with network error 7: , code 0. Failed to read psf0 header!

### ISSUE THREAD

**Issue by bjstrange** [ajmandourah/tinshop-ng#2]
I have this running in a docker container. The listing populates fine, and I get the welcome text when connecting in tinfoil, but nothing will install. Any ideas?

beginning nsp stream install
disabling sleep
network error 7: , code 0. 
Failed to read psf0 header!
enabling sleep
install failed, looking for mirror...

**Comment by ajmandourah** [comment]
does the nsp file works? I have installed a title in the morining and it worked. 
network error 7 is mainly an issue with your network.

can you elaborate more on your setup, config, reverse proxy and such . please don't include sensitve info.

**Comment by bjstrange** [comment]
I have installed them before through Awoo with no issues. I've tried a bunch of different nsp/nsz files and all give the same error.

Fresh install of Tinfoil v18.0
Atmosphere 1.7.1|S and fw v18.1.0.
I don't have any proxies setup, connecting directly to 192.168.0.203:3000 in tinfoil.

docker logs
```
tinshop  | 2024-10-14T17:31:44.416333858Z 2024/10/14 17:31:44 Added 243 games in your library
tinshop  | 2024-10-14T17:31:44.578320837Z 2024/10/14 17:31:44 Total of 243 files in your library (243 in titledb section)
tinshop  | 2024-10-14T17:31:44.578376251Z 2024/10/14 17:31:44 Total of 190 unique games in your library
tinshop  | 2024-10-14T17:31:44.578381891Z 2024/10/14 17:31:44 Tinshop available at http://0.0.0.0:3000 !
tinshop  | 2024-10-14T18:10:31.161450767Z 2024/10/14 18:10:31 Switch [0000000000000000000000000000000000000000000000000000000000000000], [HEXHEX], [18.0], [en], [HEXHEX], [HEXHEX] requesting /
```

Docker compose config
```
  tinshop:
    container_name: tinshop
    image: ghcr.io/ajmandourah/tinshop-ng:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TINSHOP_SOURCES_DIRECTORIES=/games
      - TINSHOP_WELCOMEMESSAGE=Welcome to my Tinshop!
    volumes:
      - /roms/NintendoSwitch/games:/games
      - /opt/appdata/tinshop-ng:/data  #this is where config.yaml and titles json file will live. added keys here should also be modifed in config.yaml file as /data/prod.keys 
```

config.yaml
```
debug:
    nfs: false
    nosecurity: false
    ticket: false
host: ""
keys: prod.keys
name: TinShop
nowelcomemessage: false
nsp:
    checkverified: false
protocol: http
renamefiles: "false"
reverseproxy: false
security:
    bannedtheme: []
    blacklist: []
    forwardauth: ""
    whitelist: []
sources:
    directories:
        - /games
    nfs: []
welcomemessage: Welcome to my Tinshop!
```
